extends Node3D
## Assembles the scene and runs the level loop:
##   running -> (reach the line) level complete -> R -> next, longer level
##           -> (health hits zero) game over    -> R -> retry same level
## R mid-run restarts the current level.
##
## Also owns the audio stack (all generated by tools/gen_audio.gd):
##   music  -- retro synth loop at medium volume
##   wind   -- loop whose volume/pitch scale with speed
##   city   -- quiet ambient bed
##   sfx    -- hit / jump / finish one-shots

enum GameState { RUNNING, LEVEL_COMPLETE, GAME_OVER }

# The 3D world lives in a low-res SubViewport upscaled with nearest
# filtering -- that's the full-screen pixelation. The HUD stays outside
# at native res.
@onready var viewport_frame = $ViewportFrame
@onready var background = $ViewportFrame/SubViewport/Background
@onready var track = $ViewportFrame/SubViewport/Track
@onready var zombies = $ViewportFrame/SubViewport/Zombies
@onready var pickups = $ViewportFrame/SubViewport/Pickups
@onready var boosts = $ViewportFrame/SubViewport/Boosts
@onready var trail = $ViewportFrame/SubViewport/Trail
@onready var ramps = $ViewportFrame/SubViewport/Ramps
@onready var obstacles = $ViewportFrame/SubViewport/Obstacles
@onready var player = $ViewportFrame/SubViewport/Player
@onready var camera_rig = $ViewportFrame/SubViewport/CameraRig
@onready var hud = $HUD

var level: int = 1
var state: GameState = GameState.RUNNING

# --- Style scoring ----------------------------------------------------------
# Points for landed tricks, clearing zombies airborne, near misses, and
# boost pads. Chaining events inside COMBO_WINDOW builds a multiplier;
# a hit (or letting the window lapse) drops it. Score carries across
# levels in a session and resets when a game over is retried. Best score
# persists to disk and shows on the menu.
const SAVE_PATH := "user://save.cfg"
const COMBO_WINDOW := 4.0
const SCORE_TRICK := 150
const SCORE_OVER := 200
const SCORE_UNDER := 150  # slipping beneath a drone, grounded
const SCORE_NEAR := 75
const SCORE_BOOST := 50
const SCORE_MEGA_BOOST := 125
const SCORE_HURDLE := 100  # clearing a barrier airborne
const SCORE_SMASH := 125
const SCORE_RAMPAGE := 300  # every 3rd smash chained inside one boost
const SCORE_RAMP := 75
const SCORE_FINISH := 500
## Trail color tiers (see trail.gd); crossing one plays a chime.
const TIER_THRESHOLDS := [1000, 3000, 6000, 10000]

var score: int = 0
var best_score: int = 0
var best_level: int = 1
var _streak: int = 0
var _combo_timer: float = 0.0
var _level_start_score: int = 0
var _smash_chain: int = 0

var _music: AudioStreamPlayer
var _wind: AudioStreamPlayer
var _city: AudioStreamPlayer
var _sfx: AudioStreamPlayer
var _chime: AudioStreamPlayer  # dedicated, so tier chimes layer over event sfx
var _sfx_hit: AudioStream
var _sfx_jump: AudioStream
var _sfx_finish: AudioStream
var _sfx_pickup: AudioStream

## Short READY/GO beat at the top of every run: the world is fully built
## and visible but the player holds still, so play visibly *starts* instead
## of the run already being mid-flight when the scene appears.
const INTRO_READY_TIME := 0.7
const INTRO_GO_TIME := 1.05
var _intro_timer: float = -1.0  # < 0 = no intro running
var _intro_label: Label
var _entry_fade: ColorRect


func _ready() -> void:
	# Pixelation targets a fixed internal resolution instead of a fixed
	# divisor, so desktops, browser windows, and phones of any size and
	# density all land on the same chunky-but-readable pixel grid. Re-run
	# on resize so browser window changes and phone rotation stay correct.
	_update_pixelation()
	get_viewport().size_changed.connect(_update_pixelation)

	_setup_audio()

	camera_rig.target = player
	background.set_follow_target(player)
	hud.player = player
	player.touch_controls = hud
	hud.restart_requested.connect(_advance_or_restart)

	player.damaged.connect(_on_player_damaged)
	player.died.connect(_on_player_died)
	player.jumped.connect(_on_player_jumped)
	player.tricked.connect(_on_player_tricked)
	player.trick_landed.connect(_on_trick_landed)
	player.finished.connect(_on_player_finished)
	pickups.collected.connect(_on_pickup_collected)
	zombies.zombie_passed.connect(_on_zombie_passed)
	zombies.zombie_smashed.connect(_on_zombie_smashed)
	boosts.boosted.connect(_on_boost)
	ramps.ramped.connect(_on_ramp)
	obstacles.hurdled.connect(_on_hurdle)

	_build_intro_overlay()
	_load_best()
	_start_level()

	# Entering from the menu's dip-to-black: fade the world in.
	var tween := create_tween()
	tween.tween_property(_entry_fade, "color:a", 0.0, 0.6)


## ~340 visible pixel rows on desktop, ~200 on mobile (chunkier, and far
## fewer fragments for phone GPUs).
func _update_pixelation() -> void:
	var rows := 200.0 if hud.is_mobile() else 340.0
	viewport_frame.stretch_shrink = clampi(
			roundi(get_viewport().get_visible_rect().size.y / rows), 2, 9)


## The center READY/GO card plus the entry fade, on their own layer above
## the HUD.
func _build_intro_overlay() -> void:
	var layer := CanvasLayer.new()
	layer.layer = 20
	add_child(layer)

	_entry_fade = ColorRect.new()
	_entry_fade.color = Color(0.05, 0.02, 0.09, 1.0)
	_entry_fade.size = get_viewport().get_visible_rect().size
	_entry_fade.mouse_filter = Control.MOUSE_FILTER_IGNORE
	layer.add_child(_entry_fade)

	_intro_label = Label.new()
	_intro_label.set_anchors_preset(Control.PRESET_FULL_RECT)
	_intro_label.horizontal_alignment = HORIZONTAL_ALIGNMENT_CENTER
	_intro_label.vertical_alignment = VERTICAL_ALIGNMENT_CENTER
	_intro_label.add_theme_font_override("font", hud.retro_font())
	_intro_label.add_theme_font_size_override("font_size", 64)
	_intro_label.add_theme_color_override("font_color", Color(1, 1, 1))
	_intro_label.add_theme_color_override("font_shadow_color", Color(1.0, 0.29, 0.66))
	_intro_label.add_theme_constant_override("shadow_offset_x", 4)
	_intro_label.add_theme_constant_override("shadow_offset_y", 4)
	_intro_label.visible = false
	layer.add_child(_intro_label)


func _start_level() -> void:
	state = GameState.RUNNING
	track.generate(level)
	player.setup(track)
	zombies.setup(track, player, level)
	pickups.setup(track, player, level)
	boosts.setup(track, player, level)
	ramps.setup(track, player, level)
	obstacles.setup(track, player, level)
	trail.setup(player)
	camera_rig.snap_to_target()
	hud.reset(level)
	_streak = 0
	_combo_timer = 0.0
	_smash_chain = 0
	hud.set_score(score, 1, false)
	trail.set_state(score, 1)

	# READY/GO beat: the freshly built level sits in view while the player
	# holds still, then play visibly begins.
	_intro_timer = 0.0
	_intro_label.text = "READY"
	_intro_label.visible = true
	player.set_physics_process(false)
	hud.running = false


func _process(delta: float) -> void:
	if _intro_timer >= 0.0:
		_intro_timer += delta
		if _intro_timer >= INTRO_GO_TIME:
			_intro_timer = -1.0
			_intro_label.visible = false
			player.set_physics_process(true)
			hud.running = true
		elif _intro_timer >= INTRO_READY_TIME:
			_intro_label.text = "GO!"
	# Wind rush scales with speed (silent when stopped/dead).
	var ratio: float = player.get_speed_ratio() if state == GameState.RUNNING else 0.0
	_wind.volume_db = lerpf(-42.0, -13.0, ratio)
	_wind.pitch_scale = 0.85 + ratio * 0.5

	# A smash chain only lives as long as its boost.
	if _smash_chain > 0 and not player.is_boosting():
		_smash_chain = 0

	# Combo lapses if nothing scored inside the window.
	if _combo_timer > 0.0:
		_combo_timer -= delta
		if _combo_timer <= 0.0 and _streak > 0:
			_streak = 0
			hud.set_score(score, 1, false)
			trail.break_combo()
			trail.set_state(score, 1)


func _unhandled_input(event: InputEvent) -> void:
	if event is InputEventKey and event.pressed and not event.echo and event.physical_keycode == KEY_R:
		_advance_or_restart()


func _advance_or_restart() -> void:
	match state:
		GameState.LEVEL_COMPLETE:
			level += 1
			_level_start_score = score
		GameState.GAME_OVER:
			score = 0
			_level_start_score = 0
		GameState.RUNNING:
			# Mid-run restart: drop anything scored this attempt.
			score = _level_start_score
	_start_level()


func _on_player_damaged(_health: int) -> void:
	_play_sfx(_sfx_hit)
	camera_rig.add_shake(0.45)
	# Taking a hit drops the combo.
	_streak = 0
	_combo_timer = 0.0
	hud.set_score(score, 1, false)
	trail.break_combo()
	trail.set_state(score, 1)


func _on_player_died() -> void:
	state = GameState.GAME_OVER
	_save_best_if_beaten()
	hud.show_game_over(level, score)


func _on_player_jumped() -> void:
	_play_sfx(_sfx_jump)


func _on_player_tricked(_trick_name: String) -> void:
	pass  # tricks are purely visual now; no HUD text


func _on_trick_landed(_trick_name: String) -> void:
	_add_score(SCORE_TRICK)


func _on_zombie_passed(kind: String) -> void:
	match kind:
		"over":
			_add_score(SCORE_OVER)
		"under":  # ducked a drone
			_add_score(SCORE_UNDER)
		_:
			_add_score(SCORE_NEAR)


func _on_zombie_smashed(pos: Vector3) -> void:
	var gained := _add_score(SCORE_SMASH)
	if gained > 0:
		zombies.popup_points(pos, "+%d" % gained, Color(0.55, 1.0, 1.0))
	_play_sfx(_sfx_hit, 1.5)  # pitched-up crunch, distinct from taking damage
	camera_rig.add_shake(0.15)
	player.burst_sparks()  # cyan spray off the wheels sells the impact
	player.extend_boost(0.35)
	_smash_chain += 1
	if _smash_chain % 3 == 0:
		var bonus := _add_score(SCORE_RAMPAGE)
		if bonus > 0:
			zombies.popup_points(pos + Vector3(0, 0.7, 0), "+%d" % bonus,
					Color(0.8, 0.45, 1.0))
		camera_rig.add_shake(0.3)


func _on_boost(mega: bool) -> void:
	_add_score(SCORE_MEGA_BOOST if mega else SCORE_BOOST)
	_play_sfx(_sfx_pickup, 1.9 if mega else 1.6)  # megas chirp higher
	player.burst_sparks()  # pads kick sparks too, matching the speed surge
	if mega:
		camera_rig.add_shake(0.18)  # the big surge lands with a kick
	_smash_chain = 0  # a fresh pad starts a fresh chain


func _on_ramp() -> void:
	_add_score(SCORE_RAMP)
	_play_sfx(_sfx_jump, 0.8)  # deeper whoosh than a normal ollie
	camera_rig.add_shake(0.12)


func _on_hurdle() -> void:
	_add_score(SCORE_HURDLE)
	_play_sfx(_sfx_jump, 1.25)  # brighter whoosh: cleared the bar


func _on_pickup_collected(_health: int) -> void:
	_play_sfx(_sfx_pickup)


func _on_player_finished(time: float, top_speed: float) -> void:
	state = GameState.LEVEL_COMPLETE
	var before := score
	score += SCORE_FINISH
	_check_tier(before)  # the finish bonus can cross a tier too
	_streak = 0
	_combo_timer = 0.0
	hud.set_score(score, 1, false)  # keep the corner label in sync with the panel
	trail.set_state(score, 1)

	# Per-level best time, kept in the same save file as the best score.
	var cfg := ConfigFile.new()
	cfg.load(SAVE_PATH)  # missing file is fine; starts empty
	var key := "level_%d" % level
	var prev: float = cfg.get_value("times", key, 0.0)
	var is_record: bool = prev <= 0.0 or time < prev
	if is_record:
		cfg.set_value("times", key, time)
		cfg.save(SAVE_PATH)

	_save_best_if_beaten()
	hud.show_level_complete(level, time, top_speed, score, prev, is_record)
	_play_sfx(_sfx_finish)


# --- Scoring ---------------------------------------------------------------

func _combo_mult() -> int:
	@warning_ignore("integer_division")
	var mult: int = 1 + _streak / 3
	return clampi(mult, 1, 5)


## Returns the points actually gained (post-multiplier; 0 outside a run),
## so callers can echo the amount in world-space popups.
func _add_score(points: int) -> int:
	if state != GameState.RUNNING:
		return 0
	_streak += 1
	_combo_timer = COMBO_WINDOW
	var before := score
	var gained := points * _combo_mult()
	score += gained
	hud.set_score(score, _combo_mult(), true)
	trail.set_state(score, _combo_mult())
	_check_tier(before)
	return gained


## Crossing a trail color tier gets a chime (on its own player, so event
## sfx in the same frame can't swallow it) and a nudge.
func _check_tier(before: int) -> void:
	for t in TIER_THRESHOLDS:
		if before < t and score >= t:
			_chime.stream = _sfx_finish
			_chime.pitch_scale = 1.6
			_chime.play()
			camera_rig.add_shake(0.2)
			break


func _save_best_if_beaten() -> void:
	if score <= best_score and level <= best_level:
		return
	best_score = maxi(best_score, score)
	best_level = maxi(best_level, level)
	var cfg := ConfigFile.new()
	cfg.load(SAVE_PATH)  # keep other sections (level times) intact
	cfg.set_value("best", "score", best_score)
	cfg.set_value("best", "level", best_level)
	cfg.save(SAVE_PATH)


func _load_best() -> void:
	var cfg := ConfigFile.new()
	if cfg.load(SAVE_PATH) == OK:
		best_score = cfg.get_value("best", "score", 0)
		best_level = cfg.get_value("best", "level", 1)


# --- Audio -----------------------------------------------------------------

func _setup_audio() -> void:
	_music = _make_loop_player("res://audio/music_loop.wav", -9.0)
	_wind = _make_loop_player("res://audio/wind_loop.wav", -42.0)
	_city = _make_loop_player("res://audio/city_loop.wav", -23.0)

	_sfx = AudioStreamPlayer.new()
	_sfx.volume_db = -8.0
	add_child(_sfx)

	_chime = AudioStreamPlayer.new()
	_chime.volume_db = -10.0
	add_child(_chime)
	_sfx_hit = load("res://audio/sfx_hit.wav")
	_sfx_jump = load("res://audio/sfx_jump.wav")
	_sfx_finish = load("res://audio/sfx_finish.wav")
	_sfx_pickup = load("res://audio/sfx_pickup.wav")


func _make_loop_player(path: String, volume_db: float) -> AudioStreamPlayer:
	var stream := load(path) as AudioStreamWAV
	stream.loop_mode = AudioStreamWAV.LOOP_FORWARD
	stream.loop_begin = 0
	stream.loop_end = stream.data.size() / 2  # 16-bit mono: bytes -> frames
	var p := AudioStreamPlayer.new()
	p.stream = stream
	p.volume_db = volume_db
	p.autoplay = true
	add_child(p)
	p.play()
	return p


func _play_sfx(stream: AudioStream, pitch: float = 1.0) -> void:
	if stream:
		_sfx.stream = stream
		_sfx.pitch_scale = pitch
		_sfx.play()
