extends Node3D
## Assembles the scene and runs the level loop:
##   running -> (reach the line) level complete -> R -> next, longer level
##           -> (health hits zero) game over    -> R -> retry same level
## R mid-run restarts the current level.
##
## Also owns the audio stack (all generated by tools/gen_audio.gd):
##   music  -- retro synth loop at medium volume
##   wind   -- loop whose volume/pitch scale with speed
##   city   -- quiet ambient bed
##   sfx    -- hit / jump / finish one-shots

enum GameState { RUNNING, LEVEL_COMPLETE, GAME_OVER }

# The 3D world lives in a low-res SubViewport upscaled with nearest
# filtering -- that's the full-screen pixelation. The HUD stays outside
# at native res.
@onready var viewport_frame = $ViewportFrame
@onready var background = $ViewportFrame/SubViewport/Background
@onready var track = $ViewportFrame/SubViewport/Track
@onready var zombies = $ViewportFrame/SubViewport/Zombies
@onready var pickups = $ViewportFrame/SubViewport/Pickups
@onready var boosts = $ViewportFrame/SubViewport/Boosts
@onready var trail = $ViewportFrame/SubViewport/Trail
@onready var player = $ViewportFrame/SubViewport/Player
@onready var camera_rig = $ViewportFrame/SubViewport/CameraRig
@onready var hud = $HUD

var level: int = 1
var state: GameState = GameState.RUNNING

# --- Style scoring ----------------------------------------------------------
# Points for landed tricks, clearing zombies airborne, near misses, and
# boost pads. Chaining events inside COMBO_WINDOW builds a multiplier;
# a hit (or letting the window lapse) drops it. Score carries across
# levels in a session and resets when a game over is retried. Best score
# persists to disk and shows on the menu.
const SAVE_PATH := "user://save.cfg"
const COMBO_WINDOW := 4.0
const SCORE_TRICK := 150
const SCORE_OVER := 200
const SCORE_NEAR := 75
const SCORE_BOOST := 50
const SCORE_FINISH := 500

var score: int = 0
var best_score: int = 0
var best_level: int = 1
var _streak: int = 0
var _combo_timer: float = 0.0
var _level_start_score: int = 0

var _music: AudioStreamPlayer
var _wind: AudioStreamPlayer
var _city: AudioStreamPlayer
var _sfx: AudioStreamPlayer
var _sfx_hit: AudioStream
var _sfx_jump: AudioStream
var _sfx_finish: AudioStream
var _sfx_pickup: AudioStream


func _ready() -> void:
	# Chunkier pixels on mobile (1/5 res vs 1/3 on desktop).
	if hud.is_mobile():
		viewport_frame.stretch_shrink = 5

	_setup_audio()

	camera_rig.target = player
	background.set_follow_target(player)
	hud.player = player
	player.touch_controls = hud
	hud.restart_requested.connect(_advance_or_restart)

	player.damaged.connect(_on_player_damaged)
	player.died.connect(_on_player_died)
	player.jumped.connect(_on_player_jumped)
	player.tricked.connect(_on_player_tricked)
	player.trick_landed.connect(_on_trick_landed)
	player.finished.connect(_on_player_finished)
	pickups.collected.connect(_on_pickup_collected)
	zombies.zombie_passed.connect(_on_zombie_passed)
	boosts.boosted.connect(_on_boost)

	_load_best()
	_start_level()


func _start_level() -> void:
	state = GameState.RUNNING
	track.generate(level)
	player.setup(track)
	zombies.setup(track, player, level)
	pickups.setup(track, player, level)
	boosts.setup(track, player, level)
	trail.setup(player)
	camera_rig.snap_to_target()
	hud.reset(level)
	_streak = 0
	_combo_timer = 0.0
	hud.set_score(score, 1, false)
	trail.set_state(score, 1)


func _process(delta: float) -> void:
	# Wind rush scales with speed (silent when stopped/dead).
	var ratio: float = player.get_speed_ratio() if state == GameState.RUNNING else 0.0
	_wind.volume_db = lerpf(-42.0, -13.0, ratio)
	_wind.pitch_scale = 0.85 + ratio * 0.5

	# Combo lapses if nothing scored inside the window.
	if _combo_timer > 0.0:
		_combo_timer -= delta
		if _combo_timer <= 0.0 and _streak > 0:
			_streak = 0
			hud.set_score(score, 1, false)
			trail.break_combo()
			trail.set_state(score, 1)


func _unhandled_input(event: InputEvent) -> void:
	if event is InputEventKey and event.pressed and not event.echo and event.physical_keycode == KEY_R:
		_advance_or_restart()


func _advance_or_restart() -> void:
	match state:
		GameState.LEVEL_COMPLETE:
			level += 1
			_level_start_score = score
		GameState.GAME_OVER:
			score = 0
			_level_start_score = 0
		GameState.RUNNING:
			# Mid-run restart: drop anything scored this attempt.
			score = _level_start_score
	_start_level()


func _on_player_damaged(_health: int) -> void:
	_play_sfx(_sfx_hit)
	# Taking a hit drops the combo.
	_streak = 0
	_combo_timer = 0.0
	hud.set_score(score, 1, false)
	trail.break_combo()
	trail.set_state(score, 1)


func _on_player_died() -> void:
	state = GameState.GAME_OVER
	_save_best_if_beaten()
	hud.show_game_over(level, score)


func _on_player_jumped() -> void:
	_play_sfx(_sfx_jump)


func _on_player_tricked(_trick_name: String) -> void:
	pass  # tricks are purely visual now; no HUD text


func _on_trick_landed(_trick_name: String) -> void:
	_add_score(SCORE_TRICK)


func _on_zombie_passed(kind: String) -> void:
	_add_score(SCORE_OVER if kind == "over" else SCORE_NEAR)


func _on_boost() -> void:
	_add_score(SCORE_BOOST)
	_play_sfx(_sfx_pickup, 1.6)


func _on_pickup_collected(_health: int) -> void:
	_play_sfx(_sfx_pickup)


func _on_player_finished(time: float, top_speed: float) -> void:
	state = GameState.LEVEL_COMPLETE
	score += SCORE_FINISH
	_streak = 0
	_combo_timer = 0.0
	hud.set_score(score, 1, false)  # keep the corner label in sync with the panel
	trail.set_state(score, 1)
	_save_best_if_beaten()
	hud.show_level_complete(level, time, top_speed, score)
	_play_sfx(_sfx_finish)


# --- Scoring ---------------------------------------------------------------

func _combo_mult() -> int:
	@warning_ignore("integer_division")
	var mult: int = 1 + _streak / 3
	return clampi(mult, 1, 5)


func _add_score(points: int) -> void:
	if state != GameState.RUNNING:
		return
	_streak += 1
	_combo_timer = COMBO_WINDOW
	score += points * _combo_mult()
	hud.set_score(score, _combo_mult(), true)
	trail.set_state(score, _combo_mult())


func _save_best_if_beaten() -> void:
	if score <= best_score and level <= best_level:
		return
	best_score = maxi(best_score, score)
	best_level = maxi(best_level, level)
	var cfg := ConfigFile.new()
	cfg.set_value("best", "score", best_score)
	cfg.set_value("best", "level", best_level)
	cfg.save(SAVE_PATH)


func _load_best() -> void:
	var cfg := ConfigFile.new()
	if cfg.load(SAVE_PATH) == OK:
		best_score = cfg.get_value("best", "score", 0)
		best_level = cfg.get_value("best", "level", 1)


# --- Audio -----------------------------------------------------------------

func _setup_audio() -> void:
	_music = _make_loop_player("res://audio/music_loop.wav", -9.0)
	_wind = _make_loop_player("res://audio/wind_loop.wav", -42.0)
	_city = _make_loop_player("res://audio/city_loop.wav", -23.0)

	_sfx = AudioStreamPlayer.new()
	_sfx.volume_db = -8.0
	add_child(_sfx)
	_sfx_hit = load("res://audio/sfx_hit.wav")
	_sfx_jump = load("res://audio/sfx_jump.wav")
	_sfx_finish = load("res://audio/sfx_finish.wav")
	_sfx_pickup = load("res://audio/sfx_pickup.wav")


func _make_loop_player(path: String, volume_db: float) -> AudioStreamPlayer:
	var stream := load(path) as AudioStreamWAV
	stream.loop_mode = AudioStreamWAV.LOOP_FORWARD
	stream.loop_begin = 0
	stream.loop_end = stream.data.size() / 2  # 16-bit mono: bytes -> frames
	var p := AudioStreamPlayer.new()
	p.stream = stream
	p.volume_db = volume_db
	p.autoplay = true
	add_child(p)
	p.play()
	return p


func _play_sfx(stream: AudioStream, pitch: float = 1.0) -> void:
	if stream:
		_sfx.stream = stream
		_sfx.pitch_scale = pitch
		_sfx.play()
