extends Node3D
## Assembles the scene and runs the level loop:
##   running -> (reach the line) level complete -> R -> next, longer level
##           -> (health hits zero) game over    -> R -> retry same level
## R mid-run restarts the current level.
##
## Also owns the audio stack (all generated by tools/gen_audio.gd):
##   music  -- retro synth loop at medium volume
##   wind   -- loop whose volume/pitch scale with speed
##   city   -- quiet ambient bed
##   sfx    -- hit / jump / finish one-shots

enum GameState { RUNNING, LEVEL_COMPLETE, GAME_OVER }

# The 3D world lives in a low-res SubViewport upscaled with nearest
# filtering -- that's the full-screen pixelation. The HUD stays outside
# at native res.
@onready var viewport_frame = $ViewportFrame
@onready var background = $ViewportFrame/SubViewport/Background
@onready var track = $ViewportFrame/SubViewport/Track
@onready var zombies = $ViewportFrame/SubViewport/Zombies
@onready var pickups = $ViewportFrame/SubViewport/Pickups
@onready var player = $ViewportFrame/SubViewport/Player
@onready var camera_rig = $ViewportFrame/SubViewport/CameraRig
@onready var hud = $HUD

var level: int = 1
var state: GameState = GameState.RUNNING

var _music: AudioStreamPlayer
var _wind: AudioStreamPlayer
var _city: AudioStreamPlayer
var _sfx: AudioStreamPlayer
var _sfx_hit: AudioStream
var _sfx_jump: AudioStream
var _sfx_finish: AudioStream
var _sfx_pickup: AudioStream


func _ready() -> void:
	# Chunkier pixels on mobile (1/4 res vs 1/3 on desktop).
	if hud.is_mobile():
		viewport_frame.stretch_shrink = 4

	_setup_audio()

	camera_rig.target = player
	background.set_follow_target(player)
	hud.player = player
	player.touch_controls = hud
	hud.restart_requested.connect(_advance_or_restart)

	player.damaged.connect(_on_player_damaged)
	player.died.connect(_on_player_died)
	player.jumped.connect(_on_player_jumped)
	player.tricked.connect(_on_player_tricked)
	player.finished.connect(_on_player_finished)
	pickups.collected.connect(_on_pickup_collected)

	_start_level()


func _start_level() -> void:
	state = GameState.RUNNING
	track.generate(level)
	player.setup(track)
	zombies.setup(track, player, level)
	pickups.setup(track, player, level)
	camera_rig.snap_to_target()
	hud.reset(level)


func _process(_delta: float) -> void:
	# Wind rush scales with speed (silent when stopped/dead).
	var ratio: float = player.get_speed_ratio() if state == GameState.RUNNING else 0.0
	_wind.volume_db = lerpf(-42.0, -13.0, ratio)
	_wind.pitch_scale = 0.85 + ratio * 0.5


func _unhandled_input(event: InputEvent) -> void:
	if event is InputEventKey and event.pressed and not event.echo and event.physical_keycode == KEY_R:
		_advance_or_restart()


func _advance_or_restart() -> void:
	if state == GameState.LEVEL_COMPLETE:
		level += 1
	_start_level()


func _on_player_damaged(_health: int) -> void:
	_play_sfx(_sfx_hit)


func _on_player_died() -> void:
	state = GameState.GAME_OVER
	hud.show_game_over(level)


func _on_player_jumped() -> void:
	_play_sfx(_sfx_jump)


func _on_player_tricked(_trick_name: String) -> void:
	pass  # tricks are purely visual now; no HUD text


func _on_pickup_collected(_health: int) -> void:
	_play_sfx(_sfx_pickup)


func _on_player_finished(time: float, top_speed: float) -> void:
	state = GameState.LEVEL_COMPLETE
	hud.show_level_complete(level, time, top_speed)
	_play_sfx(_sfx_finish)


# --- Audio -----------------------------------------------------------------

func _setup_audio() -> void:
	_music = _make_loop_player("res://audio/music_loop.wav", -9.0)
	_wind = _make_loop_player("res://audio/wind_loop.wav", -42.0)
	_city = _make_loop_player("res://audio/city_loop.wav", -23.0)

	_sfx = AudioStreamPlayer.new()
	_sfx.volume_db = -8.0
	add_child(_sfx)
	_sfx_hit = load("res://audio/sfx_hit.wav")
	_sfx_jump = load("res://audio/sfx_jump.wav")
	_sfx_finish = load("res://audio/sfx_finish.wav")
	_sfx_pickup = load("res://audio/sfx_pickup.wav")


func _make_loop_player(path: String, volume_db: float) -> AudioStreamPlayer:
	var stream := load(path) as AudioStreamWAV
	stream.loop_mode = AudioStreamWAV.LOOP_FORWARD
	stream.loop_begin = 0
	stream.loop_end = stream.data.size() / 2  # 16-bit mono: bytes -> frames
	var p := AudioStreamPlayer.new()
	p.stream = stream
	p.volume_db = volume_db
	p.autoplay = true
	add_child(p)
	p.play()
	return p


func _play_sfx(stream: AudioStream) -> void:
	if stream:
		_sfx.stream = stream
		_sfx.play()
